# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class DataRetentionPolicyEnum(str, enum.Enum):
    """
    The type of data retention policy on an environment
    """

    LAST_ACTIVITY = "lastActivity"
    SINCE_CREATED = "sinceCreated"

    def visit(
        self, last_activity: typing.Callable[[], T_Result], since_created: typing.Callable[[], T_Result]
    ) -> T_Result:
        if self is DataRetentionPolicyEnum.LAST_ACTIVITY:
            return last_activity()
        if self is DataRetentionPolicyEnum.SINCE_CREATED:
            return since_created()
