# This file was auto-generated by Fern from our API Definition.

from .cell_value import CellValue
import typing_extensions
import typing
from .cell_value_union import CellValueUnion
from ...core.serialization import FieldMetadata
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class DiffValue(CellValue):
    snapshot_value: typing_extensions.Annotated[
        typing.Optional[CellValueUnion], FieldMetadata(alias="snapshotValue")
    ] = None
    clip_value: typing_extensions.Annotated[typing.Optional[CellValueUnion], FieldMetadata(alias="clipValue")] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
