# This file was auto-generated by Fern from our API Definition.

from .job_execution_plan_config import JobExecutionPlanConfig
import typing_extensions
from ...commons.types.file_id import FileId
from ...core.serialization import FieldMetadata
from ...commons.types.job_id import JobId
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing
import pydantic


class JobExecutionPlanConfigRequest(JobExecutionPlanConfig):
    file_id: typing_extensions.Annotated[FileId, FieldMetadata(alias="fileId")]
    job_id: typing_extensions.Annotated[JobId, FieldMetadata(alias="jobId")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
