# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class SchemaDiffEnum(str, enum.Enum):
    ADDED = "added"
    REMOVED = "removed"
    UNCHANGED = "unchanged"

    def visit(
        self,
        added: typing.Callable[[], T_Result],
        removed: typing.Callable[[], T_Result],
        unchanged: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is SchemaDiffEnum.ADDED:
            return added()
        if self is SchemaDiffEnum.REMOVED:
            return removed()
        if self is SchemaDiffEnum.UNCHANGED:
            return unchanged()
