# This file was auto-generated by Fern from our API Definition.

import typing

from .cell_value_with_counts import CellValueWithCounts

CellsResponseData = typing.Dict[str, typing.List[CellValueWithCounts]]
