# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class EnumPropertySortBy(str, enum.Enum):
    LABEL = "label"
    VALUE = "value"
    ORDINAL = "ordinal"

    def visit(
        self,
        label: typing.Callable[[], T_Result],
        value: typing.Callable[[], T_Result],
        ordinal: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is EnumPropertySortBy.LABEL:
            return label()
        if self is EnumPropertySortBy.VALUE:
            return value()
        if self is EnumPropertySortBy.ORDINAL:
            return ordinal()
