# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class ApiKeyType(str, enum.Enum):
    PUBLISHABLE = "PUBLISHABLE"
    SECRET = "SECRET"

    def visit(self, publishable: typing.Callable[[], T_Result], secret: typing.Callable[[], T_Result]) -> T_Result:
        if self is ApiKeyType.PUBLISHABLE:
            return publishable()
        if self is ApiKeyType.SECRET:
            return secret()
