# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class JobPartExecution(str, enum.Enum):
    SEQUENTIAL = "sequential"
    PARALLEL = "parallel"

    def visit(self, sequential: typing.Callable[[], T_Result], parallel: typing.Callable[[], T_Result]) -> T_Result:
        if self is JobPartExecution.SEQUENTIAL:
            return sequential()
        if self is JobPartExecution.PARALLEL:
            return parallel()
