# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class Trigger(str, enum.Enum):
    """
    the type of trigger to use for this job
    """

    MANUAL = "manual"
    IMMEDIATE = "immediate"

    def visit(self, manual: typing.Callable[[], T_Result], immediate: typing.Callable[[], T_Result]) -> T_Result:
        if self is Trigger.MANUAL:
            return manual()
        if self is Trigger.IMMEDIATE:
            return immediate()
