# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class ListUsersSortField(str, enum.Enum):
    EMAIL = "email"
    NAME = "name"
    ID = "id"
    IDP = "idp"
    IDP_REF = "idp_ref"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"
    LAST_SEEN_AT = "last_seen_at"
    DASHBOARD = "dashboard"

    def visit(
        self,
        email: typing.Callable[[], T_Result],
        name: typing.Callable[[], T_Result],
        id: typing.Callable[[], T_Result],
        idp: typing.Callable[[], T_Result],
        idp_ref: typing.Callable[[], T_Result],
        created_at: typing.Callable[[], T_Result],
        updated_at: typing.Callable[[], T_Result],
        last_seen_at: typing.Callable[[], T_Result],
        dashboard: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is ListUsersSortField.EMAIL:
            return email()
        if self is ListUsersSortField.NAME:
            return name()
        if self is ListUsersSortField.ID:
            return id()
        if self is ListUsersSortField.IDP:
            return idp()
        if self is ListUsersSortField.IDP_REF:
            return idp_ref()
        if self is ListUsersSortField.CREATED_AT:
            return created_at()
        if self is ListUsersSortField.UPDATED_AT:
            return updated_at()
        if self is ListUsersSortField.LAST_SEEN_AT:
            return last_seen_at()
        if self is ListUsersSortField.DASHBOARD:
            return dashboard()
