# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class MappingRuleType(str, enum.Enum):
    ASSIGN = "assign"

    def visit(self, assign: typing.Callable[[], T_Result]) -> T_Result:
        if self is MappingRuleType.ASSIGN:
            return assign()
