# This file was auto-generated by Fern from our API Definition.

import typing
from .user_id import UserId
from .agent_id import AgentId
from .guest_id import GuestId

ActorIdUnion = typing.Union[UserId, AgentId, GuestId]
