# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
from .input_enum_property_option import InputEnumPropertyOption
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class InputConfig(UniversalBaseModel):
    options: typing.List[InputEnumPropertyOption]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
