# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class ValidationType(str, enum.Enum):
    ERROR = "error"
    WARN = "warn"
    INFO = "info"

    def visit(
        self,
        error: typing.Callable[[], T_Result],
        warn: typing.Callable[[], T_Result],
        info: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is ValidationType.ERROR:
            return error()
        if self is ValidationType.WARN:
            return warn()
        if self is ValidationType.INFO:
            return info()
