# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
from .field_size import FieldSize
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class FieldAppearance(UniversalBaseModel):
    """
    Control the appearance of this field when it's displayed in a table or input
    """

    size: typing.Optional[FieldSize] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
