# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from .action_mount_document import ActionMountDocument
from .action_mount_field import ActionMountField
from .action_mount_file import ActionMountFile
from .action_mount_sheet import ActionMountSheet
from .action_mount_workbook import ActionMountWorkbook


class ActionMount_Sheet(ActionMountSheet):
    type: typing.Literal["sheet"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class ActionMount_Workbook(ActionMountWorkbook):
    type: typing.Literal["workbook"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class ActionMount_Field(ActionMountField):
    type: typing.Literal["field"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class ActionMount_Document(ActionMountDocument):
    type: typing.Literal["document"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class ActionMount_File(ActionMountFile):
    type: typing.Literal["file"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


ActionMount = typing.Union[
    ActionMount_Sheet, ActionMount_Workbook, ActionMount_Field, ActionMount_Document, ActionMount_File
]
