# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class InputConstraintType(str, enum.Enum):
    REQUIRED = "required"

    def visit(self, required: typing.Callable[[], T_Result]) -> T_Result:
        if self is InputConstraintType.REQUIRED:
            return required()
