# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class InputFormType(str, enum.Enum):
    SIMPLE = "simple"

    def visit(self, simple: typing.Callable[[], T_Result]) -> T_Result:
        if self is InputFormType.SIMPLE:
            return simple()
