# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class JobPayloadType(str, enum.Enum):
    FILE = "FILE"
    PIPELINE = "PIPELINE"

    def visit(self, file: typing.Callable[[], T_Result], pipeline: typing.Callable[[], T_Result]) -> T_Result:
        if self is JobPayloadType.FILE:
            return file()
        if self is JobPayloadType.PIPELINE:
            return pipeline()
