# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
from ...commons.types.workbook_id import WorkbookId
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing
import pydantic


class GuestWorkbook(UniversalBaseModel):
    """
    Examples
    --------
    from flatfile.guests import GuestWorkbook

    GuestWorkbook(
        id="us_wb_YOUR_ID",
    )
    """

    id: WorkbookId

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
