# This file was auto-generated by Fern from our API Definition.

import typing

from ...commons.types.account_id import AccountId
from ...commons.types.environment_id import EnvironmentId
from ...commons.types.space_id import SpaceId

ResourceIdUnion = typing.Union[AccountId, EnvironmentId, SpaceId]
